version: '3'
services:
  apiget:
    image: uchima93/apiget:v1
    ports:
      - "3001:3001"
    depends_on:
      - "mongo"
  web:
    image: uchima93/apicrud:v1
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes: 
      - mongodbdata:/data/db
volumes: 
  mongodbdata: