version: '3.9'
services:
  frontend:
    image: uchima93/frontendnet:v1
    environment: 
      - backendUrl=http://apiget:3001
    ports:
      - "5902:80"
    depends_on: 
      - apiget
  apiget:
    image: uchima93/apiget:v1
    command: node index.js
    #mem_limit: 32 m #380
    #mem_limit: 64 m #60
    ports:
      - "3001:3001"
    depends_on:
      - "mongo"
  web:
    image: uchima93/apicrud:v1
    command: node index.js
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes: 
      - mongodbdata:/data/db
volumes: 
  mongodbdata: