version: '3'
services:
  web:
    image: uchima93/apicrud:v1
    command: node index.js
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    #volumes: 
    #  - mongodbdata:/data/db
#volumes: 
  #mongodbdata: