version: '3.4'

services: 

  frontend:
    image: uchima93/frontendmicroservicio:v1
    build:
      context: frontend
      dockerfile: Dockerfile
    environment: 
      - backendUrl=http://backend
    ports:
      - "5902:80"
    depends_on: 
      - backend
  backend:
    image: uchima93/backendmicroservicio:v1
    build: 
      context: backend
      dockerfile: Dockerfile
    #ports: 
      #- "5900:80"